---
- name: Deploy Microservices Application
  hosts: servers
  become: yes
  vars:
    app_repo: "https://github.com/YOUR_GITHUB_USERNAME/DevOps-Stage-6.git"
    app_dir: "/opt/microservices-app"
    acme_email: "akoredeadetunji93@gmail.com"
  
  roles:
    - dependencies
    - deploy