---
- name: Deploy Microservices Application
  hosts: servers
  become: yes
  vars:
    app_repo: "https://github.com/Masterpitan/DevOps-Stage-6.git"
    app_dir: "/opt/microservices-app"
    acme_email: "akoredeadetunji93@gmail.com"

  roles:
    - role: dependencies
      tags: [infra, dependencies]
    - role: deploy
      tags: [deploy, application]
